CREATE SCHEMA customer_behavior;

USE customer_behavior

SELECT * FROM customer_shopping_behavior
LIMIT 10
--01.What is the toal revenue generated by male v/s female customers?
SELECT gender,sum(purchase_amount)
FROM customer_shopping_behavior
GROUP BY gender

--02.Which customers used a discount but still paid more than the average purchase amount?
SELECT customer_id,purchase_amount,discount_applied
FROM customer_shopping_behavior
WHERE discount_applied = 'Yes'
AND purchase_amount > (SELECT avg(purchase_amount) FROM customer_shopping_behavior)


--03.Which are the top 5 products with highest average review rating
SELECT item_purchased,round(avg(review_rating),2) AS avg_review_rating
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC
LIMIT 5


--04.Compare the average Purchased amount between standars and express shipping
SELECT shipping_type,round(avg(purchase_amount),2) as avg_amount
FROM customer_shopping_behavior
WHERE shipping_type='Standard' or shipping_type='Express'
GROUP BY shipping_type
ORDER BY avg(purchase_amount) DESC


--05.Do subscribed customers spend more?Compare avg spend and total revenue between subscribed and non-subscribed customers
SELECT subscription_status,count(distinct customer_id) as total_customers,round(avg(purchase_amount),2) as avg_amount ,sum(purchase_amount) as total_amount
FROM customer_shopping_behavior
GROUP BY subscription_status
ORDER BY total_amount,avg_amount DESC

--06.Which 5 products have the highest percentage of purchaes with discounts applied
SELECT item_purchased,ROUND(SUM(CASE WHEN discount_applied ='Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100,2) as discount_percentage
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5

--07.Segment customers into New,Returning and loyal based on their total number of previous purchases and show count of each segment
with customer_type as
(
  SELECT customer_id,previous_purchases,
  CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer_shopping_behavior)
SELECT customer_segment,count(distinct customer_id) as total_customers
FROM customer_type
GROUP BY customer_segment
ORDER BY total_customers DESC

--08.Top 3 purchases wihtin each category
With CTE as(
SELECT category,item_purchased,COUNT(customer_id) as total_purchases,ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) as rank
FROM customer_shopping_behavior
GROUP BY category,item_purchased
)
SELECT *
from cte
where rank<=3


--09.Are customers who are repeated subscribers more likely to purchase more than 5 items?
SELECT subscription_status,COUNT(customer_id)
FROM customer_shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status

--10.What is the revenue contirbution of each age group?
SELECT age_group,sum(purchase_amount) as total_amount
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY total_amount DESC

--11.Find the top 3 customers who spent the most overall.
SELECT 
    customer_id,
    purchase_amount AS total_spent
FROM customer_shopping_behavior
ORDER BY purchase_amount DESC
LIMIT 3;

--12.What is the average purchase amount per category per season?
SELECT category,season ,ROUND(avg(purchase_amount), 2) as avg_amount 
FROM customer_shopping_behavior
GROUP BY category,season
ORDER BY category,season



